# Generated by Django 5.0.4 on 2024-04-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JavaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('javadoc_lines_count', models.IntegerField()),
                ('comment_lines_count', models.IntegerField()),
                ('code_line_count', models.IntegerField()),
                ('loc_count', models.IntegerField()),
                ('function_count', models.IntegerField()),
                ('comment_deviation_perc', models.FloatField()),
            ],
        ),
    ]
