# Generated by Django 5.0.4 on 2024-04-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YazilimTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubDepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='javaclass',
            name='github_repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='YazilimTest.githubdepo'),
        ),
    ]
